# Uncomment to enable encoder
CONFIG_EC11=n
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n

# Uncomment the following line to enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
